version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: neoledger-db
    environment:
      POSTGRES_USER: neoledger
      POSTGRES_PASSWORD: password
      POSTGRES_DB: neoledger_core
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: neoledger-cache
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus
    container_name: neoledger-metrics
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus

  grafana:
    image: grafana/grafana
    container_name: neoledger-viz
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

volumes:
  pgdata:
